{% set name = "pyribs" %}
{% set pypi_name = "ribs" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/ribs-{{ version }}.tar.gz
  sha256: bdb8e7ccc4620f448b72a16fafff96fb0961a41405ec7b2f3ecb83dd291fa156

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    # Same as pyribs-base https://github.com/conda-forge/pyribs-base-feedstock/blob/master/recipe/meta.yaml
    - decorator >=4.0.0
    - numba >=0.51.0
    - numpy >=1.17.0
    - pandas >=1.0.0
    - python >=3.6
    - scikit-learn >=0.20
    - scipy >=1.4.0
    - sortedcontainers >=2.0.0
    - threadpoolctl >=2.0.0
    - toml >=0.10.0
    # Remaining deps come from the ribs[all] extra.
    - matplotlib-base >=3.0.0

test:
  imports:
    - ribs
    - ribs.visualize
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/icaros-usc/pyribs
  summary: A bare-bones Python library for quality diversity optimization.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
