# Adapted from Gymnasium:
# https://github.com/conda-forge/gymnasium-feedstock/blob/main/recipe/meta.yaml
{% set pypi_name = "ribs" %}
{% set version = "0.5.1" %}


package:
  name: pyribs-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/ribs-{{ version }}.tar.gz
  sha256: 89b32a8f540df9cb1f9b363c91ef567fe83556337e1309e0dce78e18d27d21a0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - python
  run:
    - python >=3.7

outputs:
  - name: pyribs
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - numba >=0.51.0
        - numpy >=1.17.0
        - numpy_groupies >=0.9.16
        - pandas >=1.0.0
        - python >=3.7
        - scikit-learn >=0.20.0
        - scipy >=1.4.0
        - semantic_version >=2.10
        - sortedcontainers >=2.0.0
        - threadpoolctl >=3.0.0
    test:
      imports:
        - ribs
      commands:
        - pip check
      requires:
        - pip

  - name: pyribs-visualize
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - {{ pin_subpackage("pyribs", exact=True) }}
        - matplotlib-base >=3.0.0
    test:
      imports:
        - ribs.visualize
      commands:
        - pip check
      requires:
        - pip

  - name: pyribs-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        # Add future extras down here.
        - {{ pin_subpackage("pyribs-visualize", exact=True) }}
    test:
      imports:
        # Add extra pyribs imports here.
        - ribs
        - ribs.visualize
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/icaros-usc/pyribs
  summary: A bare-bones Python library for quality diversity optimization.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
