# Adapted from Gymnasium:
# https://github.com/conda-forge/gymnasium-feedstock/blob/main/recipe/meta.yaml
{% set pypi_name = "ribs" %}
{% set version = "0.7.0" %}


package:
  name: pyribs-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/ribs-{{ version }}.tar.gz
  sha256: 3799ef4483c6bfd4c2620301fa96781496b74e48194ccbafd76353a7c6b3944d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - python
  run:
    - python >=3.8

outputs:
  - name: pyribs
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
      noarch: python
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - numba >=0.51.0
        - numpy >=1.17.3
        - numpy_groupies >=0.9.16
        - pandas >=1.0.0
        - python >=3.8
        - scikit-learn >=1.1.0
        - scipy >=1.7.0
        - sortedcontainers >=2.0.0
        - threadpoolctl >=3.0.0
    test:
      imports:
        - ribs
      commands:
        - pip check
      requires:
        - pip

  - name: pyribs-visualize
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - {{ pin_subpackage("pyribs", exact=True) }}
        - matplotlib-base >=3.0.0
        - shapely >=2.0.0
    test:
      imports:
        - ribs.visualize
      commands:
        - pip check
      requires:
        - pip

  - name: pyribs-pycma
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - {{ pin_subpackage("pyribs", exact=True) }}
        - cma
    test:
      imports:
        - ribs
      commands:
        - pip check
      requires:
        - pip

  - name: pyribs-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        # Add future extras down here.
        - {{ pin_subpackage("pyribs-visualize", exact=True) }}
        - {{ pin_subpackage("pyribs-pycma", exact=True) }}
    test:
      imports:
        # Add extra pyribs imports here.
        - ribs
        - ribs.visualize
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/icaros-usc/pyribs
  summary: A bare-bones Python library for quality diversity optimization.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - btjanaka
